#!/bin/bash
# Make sure this script is in the HOME directory.
# Make sure there is only one athinput file per directory!

athenaPath="/software/bwong24/Athena_Radiation-master"
OUT_Path="/home/bwong24/URS_Athena_CHTC/run01"

# Athena config script
sh ${athenaPath}/makeAPP.sh

for OUTdir in $(ls -d ${OUT_PATH}/OUT*/)
do
	echo $OUTdir
	cd $OUTdir
	inputFile=$(ls athinput*)
	echo $(time (${athenaPath}/bin/athena -i $inputFile >log_run.txt))
	cd ..
done
