#!/bin/bash
#SBATCH --partition=astro3 
#SBATCH --time=0-05:00:00 #runtime in days-hh:mm:ss
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=8 #cpus per node
#SBATCH --mem=128000 #RAM per node
#SBATCH --error=job.%J.err 
#SBATCH --output=job.%J.out

# Make sure there is only one athinput file per directory!

athenaPath="/software/bwong24/Athena_Radiation-master"
OUT_Path="/home/bwong24/URS_Athena_CHTC/run01"

# Athena should ALREADY be configured at this point!

cd $OUT_Path;
inputFile=$(ls athinput*)
echo $(time (../$athenaPath/bin/athena -i $inputFile >log_run.txt))

